flat_descriptive_stats.Rmd:
  path: dev/flat_descriptive_stats.Rmd
  state: active
  R:
  - R/mean_plus.R
  - R/get_stats.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_descriptive_stats.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_fct_reorder_contam.Rmd:
  path: dev/flat_fct_reorder_contam.Rmd
  state: active
  R:
  - R/fct_reorder_pcb.R
  - R/fct_reorder_pfas.R
  tests:
  - tests/testthat/test-fct_reorder_pcb.R
  - tests/testthat/test-fct_reorder_pfas.R
  vignettes: []
  inflate:
    flat_file: dev/flat_fct_reorder_contam.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_fct_reorder_species.Rmd:
  path: dev/flat_fct_reorder_species.Rmd
  state: active
  R: R/fct_reorder_species.R
  tests: tests/testthat/test-fct_reorder_species.R
  vignettes: []
  inflate:
    flat_file: dev/flat_fct_reorder_species.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_nondetects.Rmd:
  path: dev/flat_nondetects.Rmd
  state: active
  R: R/impute_censored_with_truncated_fit.R
  tests: tests/testthat/test-impute_censored_with_truncated_fit.R
  vignettes: []
  inflate:
    flat_file: dev/flat_nondetects.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
