---
title: "flat_fct_reorder_contam.Rmd"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(chopin.magnification)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# fct_reorder_PCB

```{r function-fct_reorder_PCB}
#' fct_reorder_PCB Reorder PCB factor
#'
#' @param data dataset with column PCB
#'
#' @return data with reordered factor column
#' @export
#'
#' @examples
fct_reorder_PCB <- function(data) {
  
  reordered_data <- data |> 
    dplyr::mutate(PCB = factor(PCB, levels = c(
      "sumPCB", "CB28", "CB31", "CB44", "CB49", "CB52", 
      "CB101", "CB105", "CB110", "CB118", "CB128", "CB132", 
      "CB138", "CB149", "CB153", "CB156", "CB170", "CB180")))
  
  return(reordered_data)
}
```

```{r examples-fct_reorder_PCB}
levels(fct_reorder_PCB(BMF_species_all_PCB_ng_glw_compare)$PCB)
```

```{r tests-fct_reorder_PCB}
test_that("fct_reorder_PCB works", {
  expect_true(inherits(fct_reorder_PCB, "function"))
  expect_equal(object = levels(fct_reorder_PCB(BMF_species_all_PCB_ng_glw_compare)$PCB),
               expected = c("sumPCB", "CB28", "CB31", "CB44", "CB49", "CB52", 
      "CB101", "CB105", "CB110", "CB118", "CB128", "CB132", 
      "CB138", "CB149", "CB153", "CB156", "CB170", "CB180"))
})
```

# fct_reorder_PFAS

```{r function-fct_reorder_PFAS}
#' fct_reorder_PFAS Reorder PFAS factor
#'
#' @param data dataset with column PFAS
#'
#' @return data with reordered factor column
#' @export
#'
#' @examples
fct_reorder_PFAS <- function(data) {
  
  reordered_data <- data |> 
    dplyr::mutate(PFAS = factor(PFAS, levels = c(
      "sumPFAS", "PFPeA", "PFNA", "PFDA", "PFUnDA", "PFDoDA", "PFTrDA", "PFTeDA", 
      "FOSA", "EtFOSAA", "L-PFOS", "Br-PFOS", "6:2 FTSA", "8:2 FTSA")))
  
  return(reordered_data)
}
```

```{r examples-fct_reorder_PFAS}
levels(fct_reorder_PFAS(BMF_diet_PFAS_ng_gdw_compare)$PFAS)
```

```{r tests-fct_reorder_PFAS}
test_that("fct_reorder_PFAS works", {
  expect_true(inherits(fct_reorder_PFAS, "function"))
  expect_equal(object = levels(fct_reorder_PFAS(BMF_diet_PFAS_ng_gdw_compare)$PFAS),
               expected = c("sumPFAS", "PFPeA", "PFNA", "PFDA", "PFUnDA", "PFDoDA", "PFTrDA", 
"PFTeDA", "FOSA", "EtFOSAA", "L-PFOS", "Br-PFOS", "6:2 FTSA", 
"8:2 FTSA"))
})
```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_fct_reorder_contam.Rmd", 
               vignette_name = NA, check = FALSE)
```

