---
title: "flat_nondetects.Rmd"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(chopin.magnification)
library(fitdistrplus)
library(truncdist)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```



# impute_censored_with_truncated_fit
    
```{r development-impute_censored_with_truncated_fit}
# You can prepare the code of the impute_censored_with_truncated_fit() function here
```
  
```{r function-impute_censored_with_truncated_fit}
#' Imputing values from log-normal distribution for non-detects
#' 
#' 
#' @param data dataset of contamination variables
#' @param var character name of the variable containing uncensored data (LOQ values)
#' @param var_cens character name of the variable containing censoring information (T/F)
#' @param distribution character model distribution (default: "lnorm")
#'
#' @return vector containing imputed values when data was <LOQ
#' 
#' @export
impute_censored_with_truncated_fit <- function(data, var, var_cens, distribution = "lnorm") {
  # Raw values and information of their censorship
  obs <- data[[var]]
  cens <- data[[var_cens]]
  
  # Do nothing if there is no censored data
  if (sum(cens) == 0) return(obs)

  # Use only detected data to adjust the distribution
  detected_values <- obs[!cens & !is.na(obs)]

  # Adjustment (log-normal by default)
  fit <- fitdistrplus::fitdist(detected_values, distr = distribution)

  # For each censored value, draw a random value according to the truncated distribution [0, LOQ].
  imputed <- obs
  LOQs <- obs[cens]

  for (i in seq_along(LOQs)) {
    loq <- LOQs[i]
    if (distribution == "lnorm") {
      mlog <- fit$estimate["meanlog"]
      slog <- fit$estimate["sdlog"]
      imputed[cens][i] <- truncdist::rtrunc(n = 1, spec = "lnorm", a = 0, b = loq, meanlog = mlog, sdlog = slog)
    }
  }

  return(imputed)
}
```
  
```{r example-impute_censored_with_truncated_fit}
impute_censored_with_truncated_fit(data = contam_PFAS_ng_gdw, 
                                   var = "PFNA", var_cens = "PFNA_cen")
```
  
```{r tests-impute_censored_with_truncated_fit}
test_that("impute_censored_with_truncated_fit works", {
  expect_true(inherits(impute_censored_with_truncated_fit, "function")) 
})
```
  


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_nondetects.Rmd", 
               vignette_name = NA, check = FALSE)
```

