---
title: "Descriptive statistics"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Functions

```{r function-mean_plus}
#' mean_plus Calculation of the rounded mean excluding missing values
#'
#' @param vector Vector containing values to be summarized
#'
#' @return mean value
#' @export

mean_plus <- function(vector){
      round(mean(vector, na.rm = TRUE), digits = 2)
}
```

```{r function-median_plus}
#' median_plus Calculation of the rounded median excluding missing values
#'
#' @param vector Vector containing values to be summarized
#'
#' @return median value
#' @importFrom stats median
#' @export

median_plus <- function(vector){
      round(median(vector, na.rm = TRUE), digits = 2)
}
```

```{r function-min_plus}
#' min_plus Calculation of the rounded minimum excluding missing values
#'
#' @param vector Vector containing values to be summarized
#'
#' @return minimal value
#' @export

min_plus <- function(vector){
      round(min(vector, na.rm = TRUE), digits = 2)
}
```

```{r function-max_plus}
#' max_plus Calculation of the rounded maximum excluding missing values
#'
#' @param vector Vector containing values to be summarized
#'
#' @return maximal value
#' @export

max_plus <- function(vector){
      round(max(vector, na.rm = TRUE), digits = 2)
}
```


```{r function-stats_mean}
#' stats_mean Calculation of the mean, min and max values of a vector
#'
#' @param vector Vector containing values to be summarized
#'
#' @return character `mean[min-max]`
#' @export

stats_mean <- function(vector){
  paste0(mean_plus(vector), "[", min_plus(vector), "-", max_plus(vector), "]")
}
```

```{r function-stats_median}
#' stats_median Calculation of the median, min and max values of a vector
#'
#' @param vector Vector containing values to be summarized
#'
#' @return character `median[min-max]`
#' @export

stats_median <- function(vector){
  paste0(median_plus(vector), "[", min_plus(vector), "-", max_plus(vector), "]")
}
```

# get_stats

```{r function-get_stats}
#' get_stats Calculation of the median, min and max values of a vector from a dataset
#' 
#' @param type character "Benthos" or "Soles"
#' @param contam character ex: name and unit for a chemical concentrations
#' @param vector vector ex: chemical concentration for a chemical
#'
#' @return tibble chemical, type, median, min, max
#'
#' @export
get_stats <- function(type, contam, vector){
  res <- tibble::tibble("chemical" = contam, 
                        "type" = type, 
                        "median" = median_plus(vector),
                        "min" = min_plus(vector),
                        "max" = max_plus(vector))
  return(res)
}
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_descriptive_stats.Rmd", 
               vignette_name = NA, check = FALSE)
```

