---
title: "flat_fct_reorder_species.Rmd"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(dplyr)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# fct_reorder_species

```{r function-fct_reorder_species}
#' fct_reorder_species Reorder species metadata factors
#'
#' @param data dataset with columns species, labels, grp and alim
#'
#' @return data with reordered factor columns
#' @export
#'
#' @examples
fct_reorder_species <- function(data) {
  reordered_data <- data |> 
    dplyr::mutate(species = factor(species,
                          levels = c("Solea_solea", "Limecola_balthica", "Nucula_nitidosa", "Scrobicularia_plana",
                                     "Abra_alba", "Cerastoderma_edule", "Corbula_gibba", "Donax_vittatus",
                                     "Ensis_directus", "Spisula_subtruncata", "Corophium_volutator",
                                     "Crangon_crangon", "Lagis_koreni", "Lanice_conchilega", "Hediste_diversicolor",
                                     "Nephtys_sp", "Owenia_fusiformis")),
         labels = factor(labels,
                         levels = c("S. solea", "L. balthica", "N. nitidosa", "S. plana", "A. alba", 
                                    "C. edule", "C. gibba", "D. vittatus", "E. directus", "S. subtruncata", 
                                    "C. volutator", "C. crangon", "L. koreni", "L. conchilega", "H. diversicolor", 
                                    "Nephtys sp.", "O. fusiformis")),
         grp = factor(grp,
                      levels = c("Actinopterygii", "Bivalvia", "Crustacea", "Polychaeta")),
         alim = factor(alim, levels = c("Omnivore", "Deposivore", "Suspensivore")))
  
  return(reordered_data)
}
```

```{r examples-fct_reorder_species}
library(chopin.magnification)
levels(fct_reorder_species(contam)$species)
```

```{r tests-fct_reorder_species}
test_that("fct_reorder_species works", {
  expect_true(inherits(fct_reorder_species, "function"))
  expect_equal(object = levels(fct_reorder_species(contam)$species),
               expected =  c("Solea_solea", "Limecola_balthica", "Nucula_nitidosa", "Scrobicularia_plana", 
"Abra_alba", "Cerastoderma_edule", "Corbula_gibba", "Donax_vittatus", 
"Ensis_directus", "Spisula_subtruncata", "Corophium_volutator", 
"Crangon_crangon", "Lagis_koreni", "Lanice_conchilega", "Hediste_diversicolor", 
"Nephtys_sp", "Owenia_fusiformis"))
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_fct_reorder_species.Rmd", 
               vignette_name = NA, check = FALSE)
```

