---
title: "3.5.BMF_comparison"
format: html
---

```{r}
#| message: false
#| include: false
library(chopin.magnification)
library(tidyverse)
library(writexl)
```


# BMF comparison

```{r}
BMF_diet <- BMF_diet_all_PCB_ng_glw_compare |> 
  rename_with(~ str_remove(.x, "BMF_diet_"), .cols = starts_with("BMF_diet_")) |> 
  mutate(type = "diet")
```

```{r}
BMF_species <- BMF_species_PCB_ng_glw_summarised |> 
  mutate(type = "species")
```

```{r}
BMF_compare <- full_join(BMF_species, BMF_diet)
```


```{r}
ggplot_BMFs_compare <- ggplot(BMF_compare) +
  aes(x = PCB, y = log(median), fill = type) +
  geom_col(position = "dodge") +
  geom_errorbar(aes(ymin = log(min), ymax = log(max), colour = type), 
                position = position_dodge(width = 0.9),
                width = 0.4) +
  geom_hline(yintercept = 0) +
  scale_color_manual(values = c("#CB2027", "#009E73")) +
  labs(x = NULL, y = "Log BMF", fill = "BMF type", color = "BMF type") +
  theme(axis.text.x=element_text(size=9, angle=45, hjust=1))

ggplot_BMFs_compare
```

```{r}
ggsave(plot = ggplot_BMFs_compare, 
       filename = "results/BMF_computation_PCB_ng_glw/5.ggplot_BMFs_compare.jpg", width = 20, height = 15, units = "cm")

```
