# WARNING - Generated by {fusen} from dev/flat_fct_reorder_contam.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("fct_reorder_PCB works", {
  expect_true(inherits(fct_reorder_PCB, "function"))
  expect_equal(object = levels(fct_reorder_PCB(BMF_species_all_PCB_ng_glw)$PCB),
               expected = c("sumPCB", "CB28", "CB31", "CB44", "CB49", "CB52", 
      "CB101", "CB105", "CB110", "CB118", "CB128", "CB132", 
      "CB138", "CB149", "CB153", "CB156", "CB170", "CB180"))
})
