# WARNING - Generated by {fusen} from dev/flat_fct_reorder_contam.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("fct_reorder_PFAS works", {
  expect_true(inherits(fct_reorder_PFAS, "function"))
  expect_equal(object = levels(fct_reorder_PFAS(BMF_diet_PFAS_ng_gdw_compare)$PFAS),
               expected = c("sumPFAS", "PFPeA", "PFNA", "PFDA", "PFUnDA", "PFDoDA", "PFTrDA", 
"PFTeDA", "FOSA", "EtFOSAA", "L-PFOS", "Br-PFOS", "6:2 FTSA", 
"8:2 FTSA"))
})
