# WARNING - Generated by {fusen} from dev/flat_fct_reorder_species.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("fct_reorder_species works", {
  expect_true(inherits(fct_reorder_species, "function"))
  expect_equal(object = levels(fct_reorder_species(contam)$species),
               expected =  c("Solea_solea", "Limecola_balthica", "Nucula_nitidosa", "Scrobicularia_plana", 
"Abra_alba", "Cerastoderma_edule", "Corbula_gibba", "Donax_vittatus", 
"Ensis_directus", "Spisula_subtruncata", "Corophium_volutator", 
"Crangon_crangon", "Lagis_koreni", "Lanice_conchilega", "Hediste_diversicolor", 
"Nephtys_sp", "Owenia_fusiformis"))
})
