# WARNING - Generated by {fusen} from dev/flat_nondetects.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("impute_censored_with_truncated_fit works", {
  expect_true(inherits(impute_censored_with_truncated_fit, "function")) 
})
