# WARNING - Generated by {fusen} from dev/flat_fct_reorder_contam.Rmd: do not edit by hand # nolint: line_length_linter.

#' fct_reorder_PCB Reorder PCB factor
#'
#' @param data dataset with column PCB
#'
#' @return data with reordered factor column
#' @export
#'
#' @examples
#' levels(fct_reorder_PCB(BMF_species_all_PCB_ng_glw_compare)$PCB)
fct_reorder_PCB <- function(data) {
  
  reordered_data <- data |> 
    dplyr::mutate(PCB = factor(PCB, levels = c(
      "sumPCB", "CB28", "CB31", "CB44", "CB49", "CB52", 
      "CB101", "CB105", "CB110", "CB118", "CB128", "CB132", 
      "CB138", "CB149", "CB153", "CB156", "CB170", "CB180")))
  
  return(reordered_data)
}
