# WARNING - Generated by {fusen} from dev/flat_fct_reorder_contam.Rmd: do not edit by hand # nolint: line_length_linter.

#' fct_reorder_PFAS Reorder PFAS factor
#'
#' @param data dataset with column PFAS
#'
#' @return data with reordered factor column
#' @export
#'
#' @examples
#' levels(fct_reorder_PFAS(BMF_diet_PFAS_ng_gdw_compare)$PFAS)
fct_reorder_PFAS <- function(data) {
  
  reordered_data <- data |> 
    dplyr::mutate(PFAS = factor(PFAS, levels = c(
      "sumPFAS", "PFPeA", "PFNA", "PFDA", "PFUnDA", "PFDoDA", "PFTrDA", "PFTeDA", 
      "FOSA", "EtFOSAA", "L-PFOS", "Br-PFOS", "6:2 FTSA", "8:2 FTSA")))
  
  return(reordered_data)
}
