# WARNING - Generated by {fusen} from dev/flat_fct_reorder_species.Rmd: do not edit by hand # nolint: line_length_linter.

#' fct_reorder_species Reorder species metadata factors
#'
#' @param data dataset with columns species, labels, grp and alim
#'
#' @return data with reordered factor columns
#' @export
#'
#' @examples
#' library(chopin.magnification)
#' levels(fct_reorder_species(contam)$species)
fct_reorder_species <- function(data) {
  reordered_data <- data |> 
    mutate(species = factor(species,
                          levels = c("Solea_solea", "Limecola_balthica", "Nucula_nitidosa", "Scrobicularia_plana",
                                     "Abra_alba", "Cerastoderma_edule", "Corbula_gibba", "Donax_vittatus",
                                     "Ensis_directus", "Spisula_subtruncata", "Corophium_volutator",
                                     "Crangon_crangon", "Lagis_koreni", "Lanice_conchilega", "Hediste_diversicolor",
                                     "Nephtys_sp", "Owenia_fusiformis")),
         labels = factor(labels,
                         levels = c("S. solea", "L. balthica", "N. nitidosa", "S. plana", "A. alba", 
                                    "C. edule", "C. gibba", "D. vittatus", "E. directus", "S. subtruncata", 
                                    "C. volutator", "C. crangon", "L. koreni", "L. conchilega", "H. diversicolor", 
                                    "Nephtys sp.", "O. fusiformis")),
         grp = factor(grp,
                      levels = c("Actinopterygii", "Bivalvia", "Crustacea", "Polychaeta")),
         alim = factor(alim, levels = c("Omnivore", "Deposivore", "Suspensivore")))
  
  return(reordered_data)
}
